apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pbrp3l5hw-java-springboot
  janus-idp.io/tekton: pbrp3l5hw-java-springboot
  backstage.io/kubernetes-id: pbrp3l5hw-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pbrp3l5hw-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
